defaults: &defaults
  :log_level: warn
  :monit_bin_dir: "/usr/local/bin"
  :monit_cli_options: "-d 60 -c /path/to/monitrc"

:development:
  <<: *defaults
  :log_level: debug

:test:
  <<: *defaults

:production:
  <<: *defaults
